version: "3.7"

services:

  database:
    image: postgres:14.2-alpine
    restart: always
    env_file: .env
    volumes:
      - ./packages/api/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432
