version: "3.7"
services:
  company_db:
    image: postgres:14.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: "P@s5w0rD"
      POSTGRES_DB: "company"
    volumes:
      - ./company_database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
