version: "3.7"

services:

  database:
    image: postgres:14.2-alpine
    restart: always
    env_file: .env
    volumes:
      - ./backend/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 5432:5432

  website:
    build: ./
    env_file: .env
    stop_grace_period: 1s
    ports:
      - '5000:5000'
    volumes:
      - './:/src'
